# Generated by Django 3.0.7 on 2021-07-05 14:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Admins',
            fields=[
                ('admin_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('iddepartment', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=45, null=True)),
                ('departmentcol', models.CharField(blank=True, max_length=45, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('iddoctor', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=45, null=True)),
                ('gender', models.CharField(blank=True, max_length=45, null=True)),
                ('pressent', models.CharField(blank=True, max_length=45, null=True)),
                ('department_iddepartment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='department_iddepartment', to='Informationapp.Department')),
            ],
        ),
        migrations.CreateModel(
            name='Nurse',
            fields=[
                ('idnurse', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=45, null=True)),
                ('gender', models.CharField(blank=True, max_length=45, null=True)),
                ('pressent', models.CharField(blank=True, max_length=45, null=True)),
                ('department_iddepartmentN', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='department_iddepartmentN', to='Informationapp.Department')),
            ],
        ),
        migrations.CreateModel(
            name='Pathient',
            fields=[
                ('idpathient', models.AutoField(db_column='idPathient', primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, db_column='Name', max_length=45, null=True)),
                ('phone_field', models.IntegerField(blank=True, db_column='phone #', null=True)),
                ('gender', models.CharField(blank=True, db_column='Gender', max_length=45, null=True)),
                ('national_id', models.IntegerField(blank=True, db_column='National id', null=True)),
                ('emergency_contact_field', models.IntegerField(blank=True, db_column='emergency contact #', null=True)),
                ('doctor_iddoctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doctor_iddoctor', to='Informationapp.Doctor')),
                ('nurse_idnurseP', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nurse_idnurse', to='Informationapp.Nurse')),
            ],
        ),
        migrations.CreateModel(
            name='Receptinist',
            fields=[
                ('idreceptinist', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=45, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Rooms',
            fields=[
                ('idrooms', models.AutoField(primary_key=True, serialize=False)),
                ('filled', models.CharField(blank=True, max_length=45, null=True)),
                ('capacity', models.CharField(blank=True, max_length=45, null=True)),
                ('degree', models.CharField(blank=True, max_length=45, null=True)),
                ('department_iddepartment', models.ForeignKey(db_column='department_iddepartment', on_delete=django.db.models.deletion.CASCADE, to='Informationapp.Department')),
            ],
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('idreport', models.AutoField(primary_key=True, serialize=False)),
                ('full_report', models.TextField(blank=True, null=True)),
                ('dignose', models.TextField(blank=True, null=True)),
                ('date', models.DateField(blank=True, null=True)),
                ('treatment', models.TextField(blank=True, null=True)),
                ('required_tests', models.TextField(blank=True, null=True)),
                ('pathient_doctor_iddoctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Pathient_doctor_iddoctor', to='Informationapp.Pathient')),
                ('pathient_idpathient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Pathient_idPathient', to='Informationapp.Pathient')),
            ],
        ),
        migrations.AddField(
            model_name='pathient',
            name='receptinist_idreceptinistP',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receptinist_idreceptinistP', to='Informationapp.Receptinist'),
        ),
        migrations.CreateModel(
            name='Manger',
            fields=[
                ('idmanger', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=45)),
                ('hospital', models.CharField(blank=True, max_length=45, null=True)),
                ('admin_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Admins_admin_id', to='Informationapp.Admins')),
            ],
        ),
        migrations.CreateModel(
            name='Hospital',
            fields=[
                ('hospital_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=45)),
                ('idmanger', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Manger_idmanger', to='Informationapp.Manger')),
            ],
        ),
        migrations.AddField(
            model_name='department',
            name='hospital_hospital_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Hospital_hospital_id', to='Informationapp.Hospital'),
        ),
        migrations.CreateModel(
            name='Bed',
            fields=[
                ('idbed', models.AutoField(db_column='idBed', primary_key=True, serialize=False)),
                ('filled', models.CharField(blank=True, max_length=45, null=True)),
                ('rooms_idrooms', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rooms_idrooms', to='Informationapp.Rooms')),
            ],
        ),
        migrations.CreateModel(
            name='PathientHasHospital',
            fields=[
                ('pathient_idpathient', models.OneToOneField(db_column='Pathient_idPathient', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='Informationapp.Pathient')),
                ('hospital_hospital_id', models.ForeignKey(db_column='Hospital_ hospital ID', on_delete=django.db.models.deletion.CASCADE, to='Informationapp.Hospital')),
            ],
        ),
        migrations.CreateModel(
            name='DoctorHasHospital',
            fields=[
                ('doctor_iddoctorD', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='doctor_iddoctorD', serialize=False, to='Informationapp.Doctor')),
                ('hospital_hospital_idD', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hospital_hospital_idD', to='Informationapp.Hospital')),
            ],
        ),
    ]
